# Example configuration for House-Mate provisioning
# Create a copy of this file and make changes before running
#
#   sudo ./setup.py path-to-config.yaml
#
# Homebridge and WireGuard are mandatory and always installed,
# as is basic system configuration.

base:
  hostname: raspberrypi
  ssh: true
  vnc: true
  healthcheck: healthcheck-url-uid-here

homebridge:
  client_id: default
  port: 51826
  pin: "123-45-678"
  ui_port: 8581

  plugins:
    homebridge-2-0-shelly:
      enabled: true
    homebridge-denon-tv:
      enabled: true
    homebridge-broadlink-rm-pro:
      enabled: true
    homebridge-mqttthing:
      enabled: true
    homebridge-camera-ffmpeg:
      enabled: true
    homebridge-daikin-local:
      enabled: true
    homebridge-google-nest-sdm:
      enabled: true
    homebridge-network-presence:
      enabled: true
    homebridge-samsung-tizen:
      enabled: true
    homebridge-sprinklerd:
      enabled: true
    homebridge-tahoma:
      enabled: true

wireguard:
  endpoint: vpn.example.com:51820
  server_pubkey: "rEHMVhHPkXWanRwZsfbIG3yeNHggOiZdeNpzPEzClBk="
  address: 10.10.0.2/24
  allowed_ips: 0.0.0.0/0
  persistent_keepalive: 25

mqtt:
  enabled: true
  listener: 1883
  allow_anonymous: true

nodered:
  enabled: true
  plugins:
    node-red-contrib-homebridge-automation:
      enabled: true

pai:
  enabled: true
  endpoint: 192.168.1.50
  pc_password: "0000"
  mqtt_host: 127.0.0.1
  interface_password: paradox

aqualinkd:
  enabled: true
  panel_type: RS-8 Combo
  mqtt_address: 127.0.0.1
